name: findus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# Remove this line if you wish to publish to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:

  # clean architecture, state management  

  flutter:
    sdk: flutter
  
  # design
  flex_color_scheme: ^6.0.1
  flutter_launcher_icons: ^0.10.0
  responsive_framework: ^0.2.0
  flutter_native_splash: ^2.2.10

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # or whatever version is latest/you need

  # clean architecture
  # state management and clean structure
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0
  rx: ^0.1.3
  # service locator
  get_it: ^7.2.0 
  # routing, does no code generation oppose to autoroute
  go_router: ^5.0.5
  # allows value based equality for our classes e.g Eat() == Eat() is true
  equatable: ^2.0.5

  cached_network_image: ^3.2.2
  
  # http alternative to access an api
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
    image: "assets/images/ic_launcher.png"
    color: "#fafafa"

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # for internationalization
  generate: true

flutter_icons:
  android: true 
  ios: true 
  image_path: "assets/images/ic_launcher.png"
  web:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    background_color: "#000"
    theme_color: "#000"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    icon_size: 100 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ic_launcher.png" # current chosen png is too small!
